# Generated by Django 2.0 on 2018-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('update_time', models.CharField(choices=[(2, '2 minutes'), (10, '10 minutes'), (30, '30 minutes')], max_length=2)),
                ('phrase', models.CharField(max_length=200)),
            ],
        ),
    ]
