# Generated by Django 2.0 on 2018-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='update_time',
            field=models.CharField(choices=[('2', '2 minutes'), ('10', '10 minutes'), ('30', '30 minutes')], max_length=2),
        ),
    ]
